# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    - name: Build English Documentation
      sphinx:
        configuration: docs/source/conf.py
        output_base: en
    - name: Build Chinese Documentation
      sphinx:
        configuration: docs/source_en/conf.py
        output_base: zh

# Build documentation in the "docs/" directory with Sphinx
subprojects:
  en:
    url: https://swift.readthedocs.io/en/latest/
    repository: https://github.com/tastelikefeet/swift
  zh:
    url: https://swift.readthedocs.io/zh/latest/
    repository: https://github.com/tastelikefeet/swift

sphinx:
  configuration: docs/source/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
# formats:
#    - pdf
#    - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
   install:
      - method: pip
        path: .
        requirements: requirements/docs.txt
      - method: pip
        path: .
        requirements: requirements/framework.txt
      - method: pip
        path: .
        requirements: requirements/llm.txt
      - method: pip
        path: .
        extra_requirements:
          - pip install -U sphinx
          - pip install -U docutils